#!/usr/bin/env python3
"""Generate 200 test students for classroom-call.el testing.

Produces:
  - students.csv        : CSV roster compatible with classroom-load-csv
  - test-students.el    : Pre-built elisp plists with pinyin (no pypinyin needed at load time)

The CSV has columns: id, name, group
The .el file sets classroom-students directly.
"""

import csv
import os
import random

random.seed(42)

# Common Chinese surnames (top 100)
SURNAMES = [
    "李", "王", "张", "刘", "陈", "杨", "赵", "黄", "周", "吴",
    "徐", "孙", "胡", "朱", "高", "林", "何", "郭", "马", "罗",
    "梁", "宋", "郑", "谢", "韩", "唐", "冯", "于", "董", "萧",
    "程", "曹", "袁", "邓", "许", "傅", "沈", "曾", "彭", "吕",
    "苏", "卢", "蒋", "蔡", "贾", "丁", "魏", "薛", "叶", "阎",
]

# Common given-name characters (single or first of double)
GIVEN1_MALE = [
    "伟", "强", "磊", "军", "勇", "杰", "涛", "明", "辉", "鹏",
    "浩", "宇", "轩", "文", "博", "阳", "子", "一", "天", "泽",
    "思", "志", "国", "建", "海", "斌", "峰", "宁", "帅", "林",
    "晨", "睿", "哲", "毅", "恒", "鑫", "铭", "俊", "超", "然",
]

GIVEN1_FEMALE = [
    "芳", "敏", "静", "丽", "婷", "雪", "玲", "艳", "娟", "霞",
    "秀", "颖", "娜", "慧", "洁", "兰", "怡", "涵", "萱", "瑶",
    "思", "悦", "婉", "晴", "妮", "嘉", "琳", "诗", "雅", "芸",
    "欣", "琪", "梦", "萌", "彤", "若", "语", "馨", "菲", "月",
]

GIVEN2 = [
    "华", "平", "安", "龙", "飞", "波", "东", "生", "成", "才",
    "荣", "庆", "祥", "瑞", "康", "健", "英", "雄", "良", "德",
    "仁", "义", "忠", "孝", "诚", "信", "勤", "学", "敏", "达",
    "远", "超", "越", "立", "新", "兴", "盛", "昌", "宏", "大",
]

GROUPS = ["1班", "2班", "3班", "4班"]


def generate_name(gender: str) -> str:
    """Generate a reasonable Chinese name."""
    surname = random.choice(SURNAMES)
    pool = GIVEN1_MALE if gender == "male" else GIVEN1_FEMALE
    given1 = random.choice(pool)
    if random.random() < 0.55:
        # double-character given name
        given2 = random.choice(GIVEN2)
        return f"{surname}{given1}{given2}"
    else:
        # single-character given name
        return f"{surname}{given1}"


def name_to_pinyin(name: str) -> str:
    """Convert Chinese name to accented pinyin (matching classroom-name-pinyin)."""
    from pypinyin import lazy_pinyin, Style
    return " ".join(
        word.capitalize() for word in lazy_pinyin(name, style=Style.TONE)
    )


def main():
    random.seed(42)

    students = []
    ids = set()
    names = set()

    for i in range(200):
        student_id = f"{20240001 + i}"
        gender = "male" if random.random() < 0.52 else "female"
        group = GROUPS[i % len(GROUPS)]

        # Ensure unique names
        name = generate_name(gender)
        attempts = 0
        while name in names and attempts < 500:
            name = generate_name(gender)
            attempts += 1
        names.add(name)

        pinyin = name_to_pinyin(name)
        students.append({
            "id": student_id,
            "name": name,
            "pinyin": pinyin,
            "group": group,
        })

    # --- Write CSV ---
    csv_path = os.path.join(os.path.dirname(__file__), "students.csv")
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "name", "group"])
        for s in students:
            writer.writerow([s["id"], s["name"], s["group"]])
    print(f"Wrote {csv_path} ({len(students)} students)")

    # --- Write elisp file ---
    el_path = os.path.join(os.path.dirname(__file__), "test-students.el")
    with open(el_path, "w", encoding="utf-8") as f:
        f.write(";;; test-students.el --- Pre-generated 200 test students with pinyin\n\n")
        f.write(";; Auto-generated by generate_test_students.py\n")
        f.write(";; Load with: (load-file \"test-students.el\")\n\n")
        f.write("(setq classroom-students\n      '(")
        for i, s in enumerate(students):
            # Escape backslashes / quotes in name just in case
            name = s["name"].replace("\\", "\\\\").replace('"', '\\"')
            pinyin = s["pinyin"].replace("\\", "\\\\").replace('"', '\\"')
            comma = "" if i == len(students) - 1 else ""
            f.write(f'\n        (:id "{s["id"]}" :name "{name}" :pinyin "{pinyin}" :group "{s["group"]}"){comma}')
        f.write("))\n\n")
        f.write(";; Also reset the pool so the students are ready to use\n")
        f.write("(classroom-reset-pool)\n")
        f.write('(message "Loaded %d test students" (length classroom-students))\n\n')
        f.write("(provide 'test-students)\n")
        f.write(";;; test-students.el ends here\n")
    print(f"Wrote {el_path} ({len(students)} students)")

    # --- Print summary ---
    group_counts = {}
    for s in students:
        group_counts[s["group"]] = group_counts.get(s["group"], 0) + 1
    print(f"\nDistribution by group:")
    for g in sorted(group_counts):
        print(f"  {g}: {group_counts[g]} students")
    print(f"\nSample students:")
    for s in students[:5]:
        print(f"  {s['id']}  {s['name']}  ({s['pinyin']})  [{s['group']}]")
    print(f"  ...")
    for s in students[-3:]:
        print(f"  {s['id']}  {s['name']}  ({s['pinyin']})  [{s['group']}]")


if __name__ == "__main__":
    main()
